print('Welcome to the Predictor2000!')
a=int(input('I bet I can guess your age. First type in your favorite number.'))
b=(input('Name a sports team that has won a major competition this year.'))
c=int(input('Type in either 1000 or 10,000'))
d=input('Type in a video game that was released the year you were born.')
e=input('What is your favorite color?')
f=input('Name your favorite artist')
g=int(input('Type in a random number.'))
extra=int(input('When Fortnite was released, what year was it?'))
h=int(input(f'When {d} was released, what year was it?'))
i=input('Name a random year.')
extra2=int(input('Type "0" if your birthday has passed this year? If it is yet to come, type "1".'))
j=int(input('What was the most recent year that the Patriots won a Super Bowl?'))
k=int(input(f'What was the most recent year that {b} won a title?'))
print(f'Is your age {k-h-extra2}?')